apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "moirai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-alias
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    {{- include "moirai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
