apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-local-config
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
data:
  database_creation.ini: |
    [database_creation]
    partitioned = true