{{- /*
File: couchdb-headless-service.yaml
Description: Headless service for CouchDB StatefulSet.
*/ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-headless
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
spec:
  clusterIP: None
  ports:
    - port: 5984
      name: couchdb
  selector:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
