apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-couchdb-init
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
    "moirai/couchdb-init-hash": {{ include (print $.Template.BasePath "/couchdb-init-scripts-configmap.yaml") . | sha256sum | quote }}
    "moirai/couchdb-secret-hash": {{ include (print $.Template.BasePath "/couchdb-secrets.yaml") . | sha256sum | quote }}
    "moirai/couchdb-statefulset-hash": {{ include (print $.Template.BasePath "/couchdb-statefulset.yaml") . | sha256sum | quote }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: couchdb-init
          image: curlimages/curl:7.85.0
          env:
            - name: APP_NAME
              value: {{ .Values.app.name }}
            - name: COUCHDB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-couchdb-secret
                  key: admin-username
            - name: COUCHDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-couchdb-secret
                  key: admin-password
            - name: COUCHDB_APPLICATION_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-couchdb-secret
                  key: application-username
            - name: COUCHDB_APPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-couchdb-secret
                  key: application-password
          command:
            - sh
            - /scripts/init.sh
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              memory: "256Mi"
          volumeMounts:
            - name: init-script
              mountPath: /scripts
              readOnly: true
            - name: config
              mountPath: /configs
              readOnly: true
      volumes:
        - name: init-script
          configMap:
            name: {{ .Release.Name }}-couchdb-init-script
        - name: config
          configMap:
            name: {{ .Release.Name }}-couchdb-config
            items:
              - key: seedlistinifile
                path: seedlist.ini