{{- /*
File: couchdb-create-dbs-job.yaml
Description: Optional Job to create CouchDB databases on post-install/upgrade.
*/ -}}
{{- if .Values.couchdb.createDatabases }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-create-dbs
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
  annotations:
    "moirai/couchdb-secret-hash": {{ include (print $.Template.BasePath "/couchdb-secrets.yaml") . | sha256sum | quote }}
    "helm.sh/hook": "post-install,post-upgrade"
spec:
  template:
    spec:
      containers:
      - name: create-dbs
        image: curlimages/curl:latest
        command:
          - sh
          - -c
          - |
            set -x
            until curl -s http://{{ .Release.Name }}-{{ .Values.couchdb.name }}:5984; do
              echo "Waiting for CouchDB to be ready...";
              sleep 5;
            done
            echo "CouchDB is ready!";

            dbs="users {{- range $db := .Values.couchdb.databases }} {{$db}}{{ end -}} ""
            for db in "${dbs[@]}"; do
              echo "Checking if database exists: $db";
              if curl -s -o /dev/null -w "%{http_code}" http://{{ .Release.Name }}-{{ .Values.couchdb.name }}:5984/$db -u $COUCHDB_USER:$COUCHDB_PASSWORD | grep -q "404"; then
                echo "Creating database: $db";
                curl -X PUT http://{{ .Release.Name }}-{{ .Values.couchdb.name }}:5984/$db -u $COUCHDB_USER:$COUCHDB_PASSWORD;

                # Create a user for the database (optional)
                user_name="user_$db"
                user_password="password_$db"
                user_roles="[\"db_admin\"]" # Example role

                echo "Creating user: $user_name for database: $db"
                curl -X PUT http://{{ .Release.Name }}-{{ .Values.couchdb.name }}:5984/_users/org.couchdb.user:$user_name -u $COUCHDB_USER:$COUCHDB_PASSWORD \
                  -H "Content-Type: application/json" \
                  -d "{\"name\": \"$user_name\", \"password\": \"$user_password\", \"roles\": $user_roles, \"type\": \"user\"}";
              else
                echo "Database already exists: $db";
              fi
            done
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-secret
              key: couchdb-user
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-secret
              key: couchdb-password
      restartPolicy: OnFailure
{{- end }}
