{{- /*
File: couchdb-secret.yaml
Description: Secret holding CouchDB credentials and Erlang cookie.
*/ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-secret
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
type: Opaque
data:
  couchdb-user: {{ .Values.couchdb.credentials.user | b64enc }}
  couchdb-password: {{ .Values.couchdb.credentials.password | b64enc }}
  couchdb-erlang-cookie: {{ .Values.couchdb.erlangCookie | b64enc }}
  couchfb-cookie-auth: {{ .Values.couchdb.credentials.cookieAuth | b64enc }}
