{{- if .Values.couchdb.createAdminSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-couchdb-secret
  labels:
    app.kubernetes.io/name: {{ include "moirai.name" . }}
    helm.sh/chart: {{ include "moirai.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  adminUsername: {{ .Values.couchdb.adminUsername | b64enc | quote }}
  adminPassword: {{ .Values.couchdb.adminPassword | b64enc | quote }}
  cookieAuthSecret: {{ .Values.couchdb.cookieAuthSecret | b64enc | quote }}
{{- end }}
