apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-headless
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
spec:
  ports:
    - port: {{ .Values.couchdb.port }}
      targetPort: {{ .Values.couchdb.port }}
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}