{{- /*
File: couchdb-statefulset.yaml
Description: StatefulSet for CouchDB deployment with Erlang settings.
*/ -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-statefulset
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
  annotations:
    "moirai/couchdb-secret-hash": {{ include (print $.Template.BasePath "/couchdb-secrets.yaml") . | sha256sum | quote }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Values.couchdb.name }}-headless
  replicas: {{ .Values.couchdb.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
        {{- include "common.labels" . | nindent 8 }}
    spec:
      containers:
      - name: couchdb
        image: "{{ .Values.couchdb.image.repository }}:{{ .Values.couchdb.image.tag }}"
        imagePullPolicy: {{ .Values.couchdb.image.pullPolicy }}
        ports:
        - containerPort: 5984
          name: couchdb
        - containerPort: 4369
          name: epmd
        - containerPort: 9100
          name: erlang
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-secret
              key: couchdb-user
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-secret
              key: couchdb-password
        - name: COUCHDB_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.couchdb.name }}-secret
              key: couchdb-erlang-cookie
        # - name: COUCHDB_NODENAME
        #   value: "$(POD_NAME).{{ .Release.Name }}-{{ .Values.couchdb.name }}-headless.{{ .Release.Namespace }}.svc.cluster.local"
        - name: NODENAME
          value: "$(POD_NAME).{{ .Release.Name }}-{{ .Values.couchdb.name }}-headless.{{ .Release.Namespace }}.svc.cluster.local"
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
  volumeClaimTemplates:
  - metadata:
      name: couchdb-data
      labels:
        app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.couchdb.persistence.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.couchdb.persistence.size | default "8Gi" }}
