apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.couchdb.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
spec:
  serviceName: {{ .Release.Name }}-{{ .Values.couchdb.name }}-headless
  replicas: {{ .Values.couchdb.replicas }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Release.Name }}-couchdb
          image: "{{ .Values.couchdb.image.repository }}:{{ .Values.couchdb.image.tag }}"
          imagePullPolicy: {{ .Values.couchdb.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-couchdb-secret
                  key: username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-couchdb-secret
                  key: password
          ports:
            - containerPort: {{ .Values.couchdb.port }}
              name: couchdb
          resources:
            requests:
              ephemeral-storage: "{{ .Values.couchdb.resources.requests.ephemeralStorage }}"
              memory: "{{ .Values.couchdb.resources.requests.memory }}"
            limits:
              ephemeral-storage: "{{ .Values.couchdb.resources.limits.ephemeralStorage }}"
              memory: "{{ .Values.couchdb.resources.limits.memory }}"
          volumeMounts:
            - name: couchdb-data
              mountPath: /opt/couchdb/data
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.couchdb.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.couchdb.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    echo "Waiting for CouchDB to become available..."
                    until curl --fail -s -u "$COUCHDB_USER:$COUCHDB_PASSWORD" http://localhost:{{ .Values.couchdb.port }}/_up; do
                      sleep 5
                    done
                    echo "Creating moirai CouchDB user..."
                    curl -X PUT -u "$COUCHDB_USER:$COUCHDB_PASSWORD" \
                      http://localhost:{{ .Values.couchdb.port }}/_users/org.couchdb.user:{{ .Values.couchdb.applicationUser }} \
                      -H "Content-Type: application/json" \
                      -d '{
                            "name": "{{ .Values.couchdb.applicationUser }}",
                            "password": "{{ .Values.couchdb.applicationPassword }}",
                            "roles": ["{{ .Values.app.name }}-user"],
                            "type": "user"
                          }'
                    for db in {{ .Values.couchdb.databases }}; do
                      echo "Creating $db database..."
                      curl -X PUT -u "moirai:{{ .Values.couchdb.applicationPassword }}" http://localhost:{{ .Values.couchdb.port }}/$db
                    done
      volumes:
        - name: couchdb-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-couchdb-pvc
