# In secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-couchdb-secret
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
type: Opaque
data:
  admin-username: {{ .Values.couchdb.adminUser | b64enc }}
  admin-password: {{ .Values.couchdb.adminPassword | b64enc }}
  application-username: {{ .Values.couchdb.applicationUser | b64enc }}
  application-password: {{ .Values.couchdb.applicationPassword | b64enc }}