apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-couchdb-pvc
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.couchdb.persistence.size }}