apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-couchdb-init-script
data:
  cluster.sh: |-
    #!/bin/bash
    set -euo pipefail

    # Function to perform a curl request and check the HTTP status code.
    perform_curl() {
      local url=$1
      local data=$2
      echo "Sending request: $data"
      response=$(curl -s -w "\nHTTP_CODE:%{http_code}" -X POST -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" \
        "$url" \
        -H 'Content-Type: application/json' \
        -d "$data")
      http_code=$(echo "$response" | tail -n1 | cut -d: -f2)
      response_body=$(echo "$response" | sed '$d')
      
      if [ "$http_code" -ne 200 ]; then
        echo "Error: Request to $url failed with HTTP status code $http_code"
        echo "Response: $response_body"
        exit 1
      fi
    }

    echo "$(date) --- Cluster Setup ---"
    echo 'Waiting for CouchDB pods to be ready...'
    sleep 30

    LEADER_URL="http://${LEADER}:{{ .Values.couchdb.port }}/_cluster_setup"

    {{- if .Values.couchdb.allways_reset }}
    echo "Resetting cluster configuration on leader: $LEADER"
    reset_data='{"action": "reset_cluster"}'
    perform_curl "$LEADER_URL" "$reset_data"
    {{- end }}

    echo "Enabling cluster on leader: $LEADER"
    enable_data=$(cat <<EOF
    {
      "action": "enable_cluster",
      "bind_address": "0.0.0.0",
      "username": "$COUCHDB_ADMIN_USER",
      "password": "$COUCHDB_ADMIN_PASSWORD",
      "node_count": $REPLICA_COUNT
    }
    EOF
    )
    perform_curl "$LEADER_URL" "$enable_data"

    for i in $(seq 1 $(($REPLICA_COUNT - 1))); do
      NODE=${POD_BASE}-$i.${SERVICE_NAME}
      echo "Adding node: $NODE"
      add_data=$(cat <<EOF
    {
      "action": "add_node",
      "host": "$NODE",
      "port": {{ .Values.couchdb.port }},
      "username": "$COUCHDB_ADMIN_USER",
      "password": "$COUCHDB_ADMIN_PASSWORD"
    }
    EOF
    )
      perform_curl "$LEADER_URL" "$add_data"
    done

    echo 'Finalizing cluster setup...'
    finish_data='{"action": "finish_cluster"}'
    perform_curl "$LEADER_URL" "$finish_data"

    echo 'Cluster setup complete.'
    echo "$(date) --- End Cluster Setup ---"

  access-setup.sh: |-
    #!/bin/sh
    echo "$(date) --- Access Setup ---"
    echo "$(date) Waiting for CouchDB to become available..."
    until curl --fail -s -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ .Values.couchdb.port }}/_up; do
    echo "$(date) CouchDB not yet available, sleeping..."
    sleep 5
    done
    sleep 10
    echo "$(date) Checking if _users database exists..."
    if ! curl --fail -s -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ .Values.couchdb.port }}/_users; then
    echo "$(date) Creating _users database..."
    curl -X PUT -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ .Values.couchdb.port }}/_users
    else
    echo "$(date) _users database already exists."
    fi
    echo "$(date) Checking if {{ .Values.couchdb.applicationUsername }} CouchDB user exists..."
    if ! curl --fail -s -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ .Values.couchdb.port }}/_users/org.couchdb.user:{{ .Values.couchdb.applicationUsername }}; then
    echo "$(date) Creating moirai CouchDB user..."
    curl -X PUT -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" \
        http://${LEADER}:{{ .Values.couchdb.port }}/_users/org.couchdb.user:{{ .Values.couchdb.applicationUsername }} \
        -H "Content-Type: application/json" \
        -d '{"name": "$COUCHDB_APPLICATION_USER", "password": "$COUCHDB_APPLICATION_PASSWORD", "roles": ["${APP_NAME}-user"], "type": "user"}'
    else
    echo "$(date) moirai CouchDB user {{ .Values.couchdb.applicationUsername }} already exists."
    fi
    echo "$(date) --- End Access Setup ---"

  databases.sh: |-
    #!/bin/sh
    echo "$(date) --- Databases Setup ---"
    {{- range .Values.couchdb.databases }}
    echo "$(date) Checking if {{ . }} database exists..."
    if ! curl --fail -s -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ $.Values.couchdb.port }}/{{ . }}; then
    echo "$(date) Creating {{ . }} database..."
    curl -X PUT -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ $.Values.couchdb.port }}/{{ . }}
    else
    echo "$(date) {{ . }} database already exists."
    fi
    echo "$(date) Setting permissions for {{ $.Values.couchdb.applicationUsername }} on {{ . }}..."
    curl -X PUT -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ $.Values.couchdb.port }}/{{ . }}/_security \
    -H "Content-Type: application/json" \
    -d '{"admins": {"names": ["$COUCHDB_ADMIN_USER"], "roles": []}, "members": {"names": ["$COUCHDB_APPLICATION_USER"], "roles": ["${APP_NAME}-user"]}}'
    {{- end }}
    echo "$(date) --- End Databases Setup ---"

  verifications.sh: |-
    #!/bin/sh
    echo "$(date) --- Verifications ---"
    echo "$(date) Checking _users database..."
    if curl --fail -s -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ .Values.couchdb.port }}/_users; then
    echo "$(date) _users database exists."
    echo "$(date) URL: http://${LEADER}:{{ .Values.couchdb.port }}/_users"
    else
    echo "$(date) _users database does not exist."
    fi
    echo "$(date) Checking moirai CouchDB user..."
    if curl --fail -s -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ .Values.couchdb.port }}/_users/org.couchdb.user:{{ .Values.couchdb.applicationUsername }}; then
    echo "$(date) moirai CouchDB user exists."
    echo "$(date) URL: http://${LEADER}:{{ .Values.couchdb.port }}/_users/org.couchdb.user:{{ .Values.couchdb.applicationUsername }}"
    else
    echo "$(date) moirai CouchDB user does not exist."
    fi
    {{- range .Values.couchdb.databases }}
    echo "$(date) Checking {{ . }} database..."
    if curl --fail -s -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ $.Values.couchdb.port }}/{{ . }}; then
    echo "$(date) {{ . }} database exists."
    echo "$(date) URL: http://${LEADER}:{{ $.Values.couchdb.port }}/{{ . }}"
    else
    echo "$(date) {{ . }} database does not exist."
    fi
    {{- end }}
    {{- if gt (int .Values.couchdb.replicas) 1 }}
    echo "$(date) --- Cluster Status ---"
    echo "$(date) Checking cluster membership..."
    curl -s -u "$COUCHDB_ADMIN_USER:$COUCHDB_ADMIN_PASSWORD" http://${LEADER}:{{ .Values.couchdb.port }}/_membership
    echo "$(date) URL: http://${LEADER}:{{ .Values.couchdb.port }}/_membership"
    {{- end }}
    echo "$(date) --- Verify Application User Access ---"
    {{- range .Values.couchdb.databases }}
    echo "$(date) Attempting to access database {{ . }} with application user..."
    if curl --fail -s -u "$COUCHDB_APPLICATION_USER:$COUCHDB_APPLICATION_PASSWORD" http://${LEADER}:{{ $.Values.couchdb.port }}/{{ . }}; then
    echo "$(date) Application user can access database {{ . }}."
    echo "$(date) URL: http://${LEADER}:{{ $.Values.couchdb.port }}/{{ . }}"
    else
    echo "$(date) Application user cannot access database {{ . }}!"
    echo "$(date) Access to database {{ . }} failed."
    fi
    {{- end }}
    echo "$(date) --- End Verify Application User Access ---"
    echo "$(date) --- End Verifications ---"

  init.sh: |-
    #!/bin/sh
    set -e

    cd /scripts

    echo "$(date) --- Start CouchDB Initialization ---"
    # Set common environment variables and export them globally
    export POD_BASE={{ .Release.Name }}-{{ .Values.couchdb.name }}
    export SERVICE_NAME={{ .Release.Name }}-{{ .Values.couchdb.name }}-headless.{{ .Release.Namespace }}.svc.cluster.local
    export REPLICA_COUNT={{ .Values.couchdb.replicas }}
    export LEADER=${POD_BASE}-0.${SERVICE_NAME}

    # If clustering is required, run cluster setup using sh
    {{- if gt (int .Values.couchdb.replicas) 1 }}
    sh ./cluster.sh
    {{- end }}

    # Run access setup (creates _users database and application user)
    sh ./access-setup.sh

    # Run databases setup (creates each database and sets permissions)
    sh ./databases.sh

    # Run verifications (summary and checks)
    sh ./verifications.sh

    echo "$(date) --- End CouchDB Initialization ---"
