{{- /*
File: couchdb-service.yaml
Description: Service to expose CouchDB endpoint.
*/ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.couchdb.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
spec:
  type: ClusterIP
  ports:
    - port: 5984
      targetPort: couchdb
      name: couchdb
  selector:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
