apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-couchdb-config
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb-config
data:
  seedlistinifile: |
    [cluster]
    seedlist = {{ template "couchdb.seedlist" . }}
