apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.couchdb.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
  annotations:
    "moirai/couchdb-secret-hash": {{ include (print $.Template.BasePath "/couchdb-secrets.yaml") . | sha256sum | quote }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Values.couchdb.name }}-headless # Use headless service
  replicas: {{ .Values.couchdb.replicas }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.couchdb.name }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-couchdb-config
            items:
              - key: seedlistinifile
                path: seedlist.ini
      automountServiceAccountToken: false
      containers:
        - name: {{ .Release.Name }}-couchdb
          image: "{{ .Values.couchdb.image.repository }}:{{ .Values.couchdb.image.tag }}"
          imagePullPolicy: {{ .Values.couchdb.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: COUCHDB_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-couchdb-secret
                  key: admin-username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-couchdb-secret
                  key: admin-password
            {{- if gt (int .Values.couchdb.replicas) 1 }}
            # Clustering configurations
            - name: COUCHDB_NODE_COUNT
              value: "{{ .Values.couchdb.replicas }}"
            - name: COUCHDB_CLUSTER
              value: "true"
            - name: COUCHDB_QUORUM
              value: "{{ div (add .Values.couchdb.replicas 1) 2 }}"
            {{- end }}
            # Setup Erlang cookie from secret and node name based on pod hostname
            - name: ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-couchdb-secret
                  key: erlang-cookie
          ports:
            - containerPort: {{ .Values.couchdb.port }}
              name: couchdb
            - containerPort: {{ .Values.couchdb.epmdPort }}
              name: epmd
          resources:
            requests:
              ephemeral-storage: {{ .Values.couchdb.resources.requests.ephemeralStorage | quote }}
              memory: {{ .Values.couchdb.resources.requests.memory | quote }}
              cpu: {{ .Values.couchdb.resources.requests.cpu | quote }}
            limits:
              ephemeral-storage: {{ .Values.couchdb.resources.limits.ephemeralStorage | quote }}
              memory: {{ .Values.couchdb.resources.limits.memory | quote }}
              cpu: {{ .Values.couchdb.resources.limits.cpu | quote }}
                   livenessProbe:
            exec:
              command:
                - sh
                - -c
                - curl -G --silent --fail -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} http://localhost:5984/_up
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - curl -G --silent --fail -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} http://localhost:5984/_up
            initialDelaySeconds: 5
            periodSeconds: 10

          volumeMounts:
            - name: config
              mountPath: /opt/couchdb/etc/default.d
              readOnly: true
            - name: couchdb-data
              mountPath: /opt/couchdb/data

   volumeClaimTemplates:
    - metadata:
        name: couchdb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
