apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moirai.fullname" . }}-gemini-secret
  labels:
    app.kubernetes.io/name: {{ include "moirai.name" . }}
    helm.sh/chart: {{ include "moirai.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiKey: {{ .Values.gemini.apiKey | b64enc | quote }}
