{{- if or .Values.moirai.apiUsername .Values.moirai.apiPassword .Values.moirai.jwtSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-moirai-secret
  labels:
    app.kubernetes.io/name: {{ include "moirai.name" . }}
    helm.sh/chart: {{ include "moirai.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiUsername: {{ .Values.moirai.apiUsername | b64enc | quote }}
  apiPassword: {{ .Values.moirai.apiPassword | b64enc | quote }}
  {{- if .Values.moirai.jwtSecretKey }}
  jwtSecretKey: {{ .Values.moirai.jwtSecretKey | b64enc | quote }}
  {{- end }}
{{- end }}
