apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "moirai.fullname" . }}
  labels:
    {{- include "moirai.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "moirai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "moirai.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "moirai.serviceAccountName" . }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      initContainers:
        - name: couchdb-init
          image: curlimages/curl:latest
          env:
          - name: ENVIRONMENT
            value: {{ .Values.environment | quote }}
          - name: OLLAMA_ENDPOINT
            value: {{ .Values.ollama.endpoint | quote }}
          - name: OPEN_WEBUI_ENDPOINT
            value: {{ .Values.openWebui.endpoint | quote }}
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-couchdb-secret
                key: adminUsername
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-couchdb-secret
                key: adminPassword
          - name: COUCHDB_URI
            value: "http://$(COUCHDB_USER):$(COUCHDB_PASSWORD)@{{ .Release.Name }}-{{ .Values.couchdb.name }}-headless:5984/"
          - name: HTTP_PORT
            value: {{ .Values.service.targetPort | quote }}
          
          command:
            - sh
            - -c
            - |
              # Function to check if CouchDB is ready
              check_couchdb_ready() {
                until curl -s -o /dev/null -w "%{http_code}" http://$MOIRAI_SVC_COUCHDB_SERVICE_HOST:5984 | grep -q "200"; do
                  echo "CouchDB not yet ready, waiting..."
                  sleep 5
                done
                echo "CouchDB is ready!"
              }

              # Function to create a database if it doesn't exist
              create_database() {
                db_name=$1
                if ! curl -s -u "$COUCHDB_USER:$COUCHDB_PASSWORD" http://$MOIRAI_SVC_COUCHDB_SERVICE_HOST:5984/$db_name | grep -q '"error":"not_found"'; then
                  echo "Database '$db_name' already exists."
                else
                  echo "Creating database '$db_name'..."
                  until curl -X PUT -u "$COUCHDB_USER:$COUCHDB_PASSWORD" http://$MOIRAI_SVC_COUCHDB_SERVICE_HOST:5984/$db_name; do
                    echo "Failed to create database '$db_name', retrying..."
                    sleep 5
                  done
                  echo "Database '$db_name' created successfully."
                fi
              }

              # Check CouchDB readiness
              check_couchdb_ready

              # Create required databases
              create_database "_users"
              create_database "feeds"
              create_database "articles"
              create_database "events"

              # Get cluster status
              echo "Fetching CouchDB cluster status..."
              cluster_status=$(curl -s -u "$COUCHDB_USER:$COUCHDB_PASSWORD" http://$MOIRAI_SVC_COUCHDB_SERVICE_HOST:5984/_membership)
              echo "CouchDB Cluster Status: $cluster_status"
      containers:
        - name: {{ include "moirai.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
          - name: ENVIRONMENT
            value: {{ .Values.environment | quote }}
          - name: OLLAMA_ENDPOINT
            value: {{ .Values.ollama.endpoint | quote }}
          - name: OPEN_WEBUI_ENDPOINT
            value: {{ .Values.openWebui.endpoint | quote }}
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-couchdb-secret
                key: adminUsername
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-couchdb-secret
                key: adminPassword
          - name: COUCHDB_URI
            value: "http://$(COUCHDB_USER):$(COUCHDB_PASSWORD)@$(MOIRAI_SVC_COUCHDB_SERVICE_HOST):5984/"
          - name: HTTP_PORT
            value: {{ .Values.service.targetPort | quote }}
          - name: ALLOW_PUBLIC_READ
            value: {{ .Values.allowPublicRead | quote }}
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-openai-secret
                key: apiKey
          - name: API_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "moirai.fullname" . }}-moirai-secret
                key: apiUsername
          - name: API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "moirai.fullname" . }}-moirai-secret
                key: apiPassword
          - name: COUCHDB_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-couchdb-secret
                key: cookieAuthSecret
          volumeMounts:
            - name: feeds-volume
              mountPath: /app/feeds
      volumes:
        - name: feeds-volume
          configMap:
            name: {{ include "moirai.fullname" . }}-feed-lists
