apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "moirai.serviceAccountName" . }}
  labels:
    {{- include "moirai.labels" . | nindent 4 }}
automountServiceAccountToken: false

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "moirai.fullname" . }}
  labels:
    {{- include "moirai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "moirai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - protocol: TCP
      name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsTargetPort }}