apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.name }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  serviceName: {{ .Values.mongodb.name }}-headless
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.mongodb.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
