apiVersion: v1
kind: Service
metadata:
  name: {{ include "moirai.fullname" . }}-nginx
  labels:
    {{- include "moirai.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    {{- include "moirai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
