# Default values for GenAI Press Review service
replicaCount: 1
image:
  repository: slorba/morai
  tag: "latest"

ingress:
  host: my-app.example.com

service:
  name: morai-service
  port: 80
  targetPort: 8080

app:
  name: morai-app

deployment:
  name: morai-deployment
  replicas: 3

environment: production

persistentVolume:
  name: morai-pv
  storage: 10Gi

persistentVolumeClaim:
  name: morai-pvc
  storage: 10Gi
  accessMode: ReadWriteOnce

ollama:
  endpoint: "https://ollama.example.com"

openWebui:
  endpoint: "https://open-webui.example.com"