name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: couchdb:3.1.1
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: password
        ports:
          - 5984:5984

    steps:
    - uses: actions/checkout@v3

    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        environment-file: environment.yml
        activate-environment: moirai
        auto-activate-base: false
        use-mamba: true

    - name: Install dependencies (Conda)
      # Dependencies are installed by setup-miniconda using environment.yml
      run: |
        echo "Conda environment 'moirai' created and activated."
        conda info -e # Display info about environments

    - name: Lint with Ruff
      run: |
        conda run --name moirai ruff check . --select=E9,F63,F7,F82 --target-version=py310 # Use conda run
        conda run --name moirai ruff check . --exit-zero --statistics # Use conda run

    - name: Run tests
      env:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: password
        COUCHDB_HOST: localhost
        COUCHDB_PORT: 5984
        API_USERNAME: testuser
        API_PASSWORD: testpassword
        FLASK_ENV: test
        TESTING: true
      run: |
        conda run --name moirai pytest # Use conda run
  
  ui-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: ui/yarn.lock

    - name: Install dependencies (Yarn)
      working-directory: ./ui
      run: yarn install

    - name: Build UI
      working-directory: ./ui
      run: yarn build

    - name: Install Playwright Browsers
      working-directory: ./ui
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: ./ui
      run: |
        sleep 30
        npx playwright test
