name: Build and Push Docker Image (amd64 & arm64)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - '.github/workflows/helm-package.yml'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run backend tests
        env:
          API_USERNAME: testuser
          API_PASSWORD: testpassword
        run: |
          PYTHONPATH=. pytest
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ui/yarn.lock
          
      - name: Install Frontend dependencies
        working-directory: ui
        run: yarn install
        
      - name: Install Playwright Browsers
        working-directory: ui
        run: npx playwright install --with-deps chromium
        
      - name: Run Playwright tests
        working-directory: ui
        run: yarn playwright test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Metadata
        uses: docker/metadata-action@v5
        id: docker_meta
        with:
          images: |
            slorba/moirai
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            slorba/moirai:latest
          labels: ${{ steps.docker_meta.outputs.labels }}