name: Build and Upload Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/helm-package.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Get Dependencies
        run: |
          cd helm
          helm dependency update

      - name: Package Helm chart
        id: package_chart
        run: |
          CHART_NAME=$(helm show chart ./helm | grep '^name:' | awk '{print $2}')
          CHART_VERSION=$(helm show chart ./helm | grep '^version:' | awk '{print $2}')
          helm package ./helm
          echo "chart_name=$CHART_NAME" >> $GITHUB_OUTPUT
          echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Helm package
        run: |
          helm push ${{ steps.package_chart.outputs.chart_name }}-${{ steps.package_chart.outputs.chart_version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
